#define DOCTEST_CONFIG_COLORS_NONE
#define DOCTEST_CONFIG_NO_SHORT_MACROS
#define DOCTEST_CONFIG_SUPER_FAST_ASSERTS
#include <doctest.h>

#define check_eq  DOCTEST_FAST_CHECK_EQ
#define subcase   DOCTEST_SUBCASE
#define test_case DOCTEST_TEST_CASE
